### ISSUE TITLE
Low accuracy for Multi Class Classification on CelebA

### ISSUE THREAD

**Issue by iamsh4shank** [bwconrad/vit-finetune#5]
Hello, 

Thank you for creating this wonderful project. I wanted to use multi-class classification using the CelebA dataset. In the case, I replace the CE Loss with BCE Loss and as the CelebA contains 40 different face attributes I modified the way of accuracy calculation as - 

```
def pred_acc(original, predicted):
    return torch.round(predicted).eq(original).sum().cpu().numpy()/len(original)
```
Here original and predicted is an array of sie [batch_size, 40]

the way I modified the shared_step is 

```
if mode == "test":
            my_acc = []
            probabilities = F.sigmoid(pred)
            for i, d in enumerate(probabilities, 0):
                acc_ = pred_acc(torch.Tensor.cpu(y[i]), torch.Tensor.cpu(d))
                my_acc.append(acc_)
            #keeping previous things undisturbed
            self.test_metric_outputs.append(metrics["stats"])
            f_acc = np.asarray(my_acc).mean()
            self.my_test.append(f_acc)
```
and on_test_epoch_end as

```
print ('ACC-----> ',np.asarray(self.my_test).mean())
```

So in this case the accuracy is like - 49 percent for size 128,128 (for reference the actual size is 178,218)

It would be great if you could help me to fix this.

**Comment by bwconrad** [comment]
First I would make sure that your accuracy calculation is correct. You can modify the current accuracy calculation to work for your problem by changing from `task="multiclass"`  to `task="multilabel"`. 

https://github.com/bwconrad/vit-finetune/blob/dfccfbe9f514472fe38290254af99ac60c3230f8/src/model.py#L180-L189

Check the [torchmetric docs](https://torchmetrics.readthedocs.io/en/stable/classification/accuracy.html#multilabelaccuracy) if you want to change how the averaging is being applied.

**Comment by iamsh4shank** [comment]
> First I would make sure that your accuracy calculation is correct. You can modify the current accuracy calculation to work for your problem by changing from `task="multiclass"` to `task="multilabel"`.
> 
> https://github.com/bwconrad/vit-finetune/blob/dfccfbe9f514472fe38290254af99ac60c3230f8/src/model.py#L180-L189
> 
> Check the [torchmetric docs](https://torchmetrics.readthedocs.io/en/stable/classification/accuracy.html#multilabelaccuracy) if you want to change how the averaging is being applied.

So does it look correct?

**Comment by bwconrad** [comment]
What I'm saying is you should compare your code with torchmetric to see if that's the issue.
